server:
  port: 8080

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ZWR1Y29uc3VsdGFuY3lzeXN0ZW0gaXMgYSBwcm9qZWN0IGkgYW0gYnVpbGRpbmcgYXMgYW4gaW50ZXJuIGF0IGluZm9zeXMgc3ByaW5nYm9hcmQ=
  expiration: 3600000