server:
  port: 8081

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true

security:
  enabled: true

jwt:
  secret: ZWR1Y29uc3VsdGFuY3lzeXN0ZW0gaXMgYSBwcm9qZWN0IGkgYW0gYnVpbGRpbmcgYXMgYW4gaW50ZXJuIGF0IGluZm9zeXMgc3ByaW5nYm9hcmQ=
  expiration: 3600000
  refresh-expiration: 604800000
  forgot-expiration: 900000

resend:
  key: re_fgWQ8DLw_28pKziHpKst9ybLdwqPjQc1W
  from-email: onboarding@resend.dev


